# Generated by Django 5.1.5 on 2025-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_rename_expectation_salary_candidate_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curr_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
