# Generated by Django 5.1.5 on 2025-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_alter_candidate_curr_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='industry',
            field=models.CharField(default='industry', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='major',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
