# Generated by Django 5.1.5 on 2025-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_alter_experience_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('seniority_level', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('sub_industry', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('requirement_details', models.TextField()),
                ('recruiter_email', models.CharField(max_length=255)),
                ('recruiter_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
