# Generated by Django 5.1.5 on 2025-01-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_poster',
            field=models.ImageField(blank=True, null=True, upload_to='job_poster/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
