# Generated by Django 5.1.5 on 2025-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_job_job_poster_alter_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
